<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="ProjetoWebApp._Default" %>
<%@ Register Src="~/UserControls/MenuSimples.ascx" TagName="MenuSimples" TagPrefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    </asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <uc1:MenuSimples ID="MenuSimples1" runat="server" />

    <asp:Button ID="btnCarregarDados" runat="server" OnClick="btnCarregarDados_Click" Text="Carregar Dados" />

    <asp:GridView ID="gdvDados" runat="server" style="margin-right: 0px" OnRowDeleting="gdvDados_RowDeleting" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="gdvDados_RowEditing" OnRowUpdating="gdvDados_RowUpdating" OnRowCancelingEdit="gdvDados_RowCancelingEdit" DataKeyNames="ID">
    </asp:GridView>

    <asp:Label ID="lblMensagem" runat="server" Text=""></asp:Label>

</asp:Content>