<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="ProjetoWebApp._Default" %>
<%@ Register Src="~/UserControls/MenuSimples.ascx" TagName="MenuSimples" TagPrefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    </asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <uc1:MenuSimples ID="MenuSimples1" runat="server" />

    <asp:Button ID="btnCarregarDados" runat="server"
        OnClick="btnCarregarDados_Click"
        Text="Carregar Dados" />

    <asp:GridView ID="gdvDados" runat="server"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        OnRowDeleting="gdvDados_RowDeleting"
        OnRowEditing="gdvDados_RowEditing"
        OnRowUpdating="gdvDados_RowUpdating"
        OnRowCancelingEdit="gdvDados_RowCancelingEdit"
        DataKeyNames="ID"
        
        CellPadding="5"
        GridLines="None"
        BackColor="#F7F7F7"
        BorderWidth="1px"
        BorderStyle="Solid"
        BorderColor="#CCCCCC"> <%-- customizacao da grid --%>
        
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="true" ForeColor="#F7F7F7"/> <%-- customizacao do header da grid --%>
        <RowStyle BackColor="#E3EAEB" /> <%-- linha da grid --%>
        <AlternatingRowStyle BackColor="#F7F7F7" /> <%-- linha alternada da grid --%>
    </asp:GridView>

    <asp:Label ID="lblMensagem" runat="server" Text=""></asp:Label>

</asp:Content>