<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="ProjetoWebApp._Default" %>
<%@ Register Src="~/UserControls/MenuSimples.ascx" TagName="MenuSimples" TagPrefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <uc1:MenuSimples ID="MenuSimples1" runat="server" />

    <div class="m-4">

        <h3>Lista de Pacientes</h3>
        
        <div class="m-4">
            <asp:Button ID="btnCarregarDados" runat="server" OnClick="btnCarregarDados_Click" Text="Carregar Dados" 
            CssClass="btn btn-secondary my-2" />
            <asp:Label ID="lblMensagem" runat="server" Text="(Informativos)" 
                CssClass="alert alert-info m-5" />
        </div>

        <asp:GridView ID="gdvDados" runat="server"
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true"
            OnRowDeleting="gdvDados_RowDeleting"
            OnRowEditing="gdvDados_RowEditing"
            OnRowUpdating="gdvDados_RowUpdating"
            OnRowCancelingEdit="gdvDados_RowCancelingEdit"
            DataKeyNames="ID"
            CssClass="table table-striped table-hover table-bordered" /> <%-- customizacao da grid com o bootstrap --%>

    </div>

</asp:Content>