<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ProjetoWebApp._Default" %>
<%@ Register Src="~/UserControls/MenuSimples.ascx" TagName="MenuSimples" TagPrefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    </asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <uc1:MenuSimples ID="MenuSimples1" runat="server" />

    <asp:Label ID="lblMensagem" runat="server" Text="Label"></asp:Label>
    <asp:Button ID="btnCarregarDados" runat="server" OnClick="btnCarregarDados_Click" Text="Carregar Dados" />

    <asp:GridView ID="gdvDados" runat="server" style="margin-right: 0px" OnRowDeleting="gdvDados_RowDeleting" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="gdvDados_RowEditing" OnRowUpdating="gdvDados_RowUpdating" OnRowCancelingEdit="gdvDados_RowCancelingEdit" DataKeyNames="ID">
    </asp:GridView>

    <asp:Panel ID="pnlCadastro" runat="server" Height="60px">
        <asp:Label ID="lblNome" runat="server" Text="Nome:"></asp:Label>
        <asp:TextBox ID="txtNome" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="rfvNome0" runat="server" ControlToValidate="txtNome" ErrorMessage="O nome é obrigatório." ValidationGroup="CadastroGroup"></asp:RequiredFieldValidator>

        <asp:Label ID="lblValor" runat="server" Text="Valor:"></asp:Label>
        <asp:TextBox ID="txtValor" runat="server"></asp:TextBox>
        <asp:RequiredFieldValidator ID="rfvValor" runat="server" ControlToValidate="txtValor" ErrorMessage="O valor é obrigatório." ValidationGroup="CadastroGroup"></asp:RequiredFieldValidator>
    </asp:Panel>

    <asp:Button ID="btnSalvar" runat="server" Text="Salvar Paciente" OnClick="btnSalvar_Click" ValidationGroup="CadastroGroup"/>

</asp:Content>