<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ProjetoWebApp._Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <style type="text/css">
        #form1 {
            height: 265px;  
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">

        <asp:Label ID="lblMensagem" runat="server" Text="Label"></asp:Label>
        <asp:Button ID="btnCarregarDados" runat="server" OnClick="btnCarregarDados_Click" Text="Carregar Dados" />

        <asp:GridView ID="gdvDados" runat="server" style="margin-right: 0px" OnRowDeleting="gdvDados_RowDeleting" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="gdvDados_RowEditing" OnRowUpdating="gdvDados_RowUpdating" OnRowCancelingEdit="gdvDados_RowCancelingEdit" DataKeyNames="ID">
        </asp:GridView>

        <asp:Panel ID="pnlCadastro" runat="server" Height="60px">
            
            <asp:Label ID="lblNome" runat="server" Text="Nome:"></asp:Label>
            <asp:TextBox ID="txtNome" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvNome0" runat="server" ControlToValidate="txtNome" ErrorMessage="O nome é obrigatório." ValidationGroup="CadastroGroup"></asp:RequiredFieldValidator>

            <asp:Label ID="lblValor" runat="server" Text="Valor:"></asp:Label>
            <asp:TextBox ID="txtValor" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvValor" runat="server" ControlToValidate="txtValor" ErrorMessage="O valor é obrigatório." ValidationGroup="CadastroGroup"></asp:RequiredFieldValidator>

        </asp:Panel>

        <asp:Button ID="btnSalvar" runat="server" Text="Salvar Paciente" OnClick="btnSalvar_Click" ValidationGroup="CadastroGroup"/>

    </form>
</body>
</html>
